name: release
on: 
    workflow_dispatch:
    push:
        branches:
            - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - name: Upload artifact to GitHub Releases
        run: |
            version="v$(node -p "require('./package.json').version")"
            gh release create $version ./dist/resources/extension-trivy.tar
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}